### ISSUE TITLE
Nav_Host_Fragment Not Recognized 

### ISSUE THREAD

**Issue by thihaaungpol18** [udacity/andfun-kotlin-mars-real-estate#11]
My nav_graph can't recognize nav_host_fragment,
So I use two activities instead

**Comment by SudKul** [comment]
@thihaaungpol18 
Not enough details are available to investigate the issue. Please provide the following to replicate the issue:
1. Branch name
2. Filename
3. Error details
4. Snapshot of the error from the emulator
