### ISSUE TITLE
Solution code for exercise 1 doesn't compile

### ISSUE THREAD

**Issue by lswitaj** [udacity/andfun-kotlin-mars-real-estate#12]
![image](https://user-images.githubusercontent.com/24640634/95717896-f36e6900-0c6d-11eb-95a4-1e4e722fa374.png)

**Comment by Das-co** [comment]
Try adding
`implementation "com.squareup.retrofit2:converter-scalars:$version_retrofit"`
in the Gradle if it can't find ScalarsConverterFactory

**Comment by lswitaj** [comment]
Maybe the problem is the following fun?
`suspend fun getProperties(): List<MarsProperty>
            Call<String>`

Shouldn't it be like the following?
`fun getProperties(): Call<String>`

**Comment by Adarsh-Adk** [comment]
I have the same problem too

**Comment by Das-co** [comment]
I think it should be like that too. Its at least stated in the course like that:

`interface MarsApiService {
 @GET("realestate")
 fun getProperties():
         Call<String>
}`

"Suspend" will be used once coroutines are introduced in the course.

**Comment by lampapos** [comment]
It's because `implementation "com.squareup.retrofit2:converter-scalars:$version_retrofit"` is commented (and marked as deprecated). It's a little bit confusing because it is required for the first step (before we start using Moshi)

**Comment by SudKul** [comment]
The [Step.01-Solution-Making-Mars-Web-Service-Contact](https://github.com/udacity/andfun-kotlin-mars-real-estate/tree/Step.01-Solution-Making-Mars-Web-Service-Contact) has been fixed. The following two files were updated:
1. app/build.gradle
2. app/src/main/java/com/example/android/marsrealestate/network/MarsApiService.kt

See the changes [here](https://github.com/udacity/andfun-kotlin-mars-real-estate/commit/d4c05b202d66c7d4bed9de2bc787d824576f23a1).

**Comment by Tarek-Bohdima** [comment]
i still have Unresolved reference: ScalarsConverterFactory

**Comment by Tarek-Bohdima** [comment]
fixed it by adding mavenCentral() in build.gradle (project) in repositories{}  : 
```
repositories {
        google()
        jcenter()
        mavenCentral()
    }
```
and all projects {}  : 

```
allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
    }
```
