### ISSUE TITLE
Solution to Exercise 6 - displays too small loading spinner

### ISSUE THREAD

**Issue by lswitaj** [udacity/andfun-kotlin-mars-real-estate#13]
Hello guys, I'd recommend using
`android:layout_width="match_parent"
android:layout_height="match_parent"`
in `fragment_overview.xml` instead of `wrap_content`.
The result - the user has a spinner on the whole screen instead of a minuscule one.

Best,
Ł

**Comment by MadhavKwatra** [comment]
Thanks
took a while to figure out that in imageViews
