### ISSUE TITLE
Updates to the code mean it no longer corresponds to the online course!

### ISSUE THREAD

**Issue by richardgledhill** [udacity/andfun-kotlin-mars-real-estate#15]
I understand that some people feel the desire to update the code to use changes such as moshi instead of the original retrofit2 library, but in doing so you are making it **_impossible to work through the course video tutorial_**.

Please provide zip files or branches corresponding to the Udacity video online as currently the change to using moshi has made it impossible to use the video to learn about retrofit.

And... please resist the temptation to change any source code on here unless the video is changed too.  You are not helping, you making it extremely hard for people trying to learn!

Thank you.

**Comment by zapp42** [comment]
I agree with Richard here. I am struggeling with the course now, too.

**Comment by richardgledhill** [comment]
I found that by looking at the gradle files, you can find the commented-out lines which can be re-enabled to get rid of the Moshi references.  This way it should be possible to work through the course.
