### ISSUE TITLE
(Step.03-Exercise-Using-Retrofit-With-Coroutines) - particularly CoroutineCallAdapterFactory dependency

### ISSUE THREAD

**Issue by dev-lester94** [udacity/andfun-kotlin-mars-real-estate#18]
For the app gradle dependencies for coroutines and the retrofit coroutines adapter it says that those are depreciated and not required anymore. I have an issue that when adding the Coroutine adapter to the Retrofit builder, .addCallAdapterFactory(CoroutineCallAdapterFactory()), that it can not resolve CoroutineCallAdapterFactory(). I did add back the dependencies to fix the issue and works but the comments says that is not required to do so. What to do here?

**Comment by Anthony-Zou** [comment]
leave it and proceed with 
3.Change getProperties() Call<List<MarsProperty>> to a Deferred list of MarsProperty:
`Deferred<List<MarsProperty>>`
