### ISSUE TITLE
minSdkVersion below 21 , cases an error

### ISSUE THREAD

**Issue by yasseramonem** [udacity/andfun-kotlin-mars-real-estate#19]
upon first run of the project with minSdkVersion set to 19 , i ran into 

`Error: null, Cannot fit requested classes in a single dex file
`

upon a few searches i found out that below 21 i had to add 

`implementation 'com.android.support:multidex:1.0.3'
`

and in the defaultConfig section

```
defaultConfig {

    multiDexEnabled true

    .........
}
```

Sdk Version 21>  has mutiDexEnabled by default and library isn't needed

**Comment by SudKul** [comment]
We will incorporate this suggestion in the next commit.
