### ISSUE TITLE
bad context ?

### ISSUE THREAD

**Issue by bugsfunny** [udacity/andfun-kotlin-mars-real-estate#7]
https://github.com/udacity/andfun-kotlin-mars-real-estate/blob/6962a5ce48de528bb612fdab55bd99edd5750158/app/src/main/res/layout/fragment_overview.xml#L33

in this line you put MainActivity... why not FragmentOverview ?

**Comment by SudKul** [comment]
We recommend you use the https://knowledge.udacity.com/ platform to discuss individual issues with our experienced mentors so that new students can benefit from the discussion.
