### ISSUE TITLE
Loading Animation not showing up

### ISSUE THREAD

**Issue by Dawson557** [udacity/andfun-kotlin-mars-real-estate#8]
I'm going through the Udacity tutorials and got confused when I couldn't seem to get the loading animation to work. I added high priority to the RequestOptions() with .priority(Priority.HIGH) and now I can actually see the loading screen.

**Comment by SudKul** [comment]
We recommend you use the https://knowledge.udacity.com/ platform to discuss individual issues with our experienced mentors so that new students can benefit from the discussion.
